"""baseline existing schema

Revision ID: 0826560045b9
Revises: 
Create Date: 2026-08-21 15:40:04.845202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0826560045b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_member_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'member', ['member_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('edit_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('edit_history_actor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('edit_history_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'gym_owner', ['actor_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'gym_owner', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('member_owner_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('member_current_plan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'membership_plan', ['current_plan_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'gym_owner', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('membership_member_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('membership_plan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'membership_plan', ['plan_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'member', ['member_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('membership_plan', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('membership_plan_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'gym_owner', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('owner_payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('owner_payment_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'gym_owner', ['owner_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner_payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('owner_payment_owner_id_fkey'), 'gym_owner', ['owner_id'], ['id'])

    with op.batch_alter_table('membership_plan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('membership_plan_owner_id_fkey'), 'gym_owner', ['owner_id'], ['id'])

    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('membership_plan_id_fkey'), 'membership_plan', ['plan_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('membership_member_id_fkey'), 'member', ['member_id'], ['id'])

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('member_current_plan_id_fkey'), 'membership_plan', ['current_plan_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('member_owner_id_fkey'), 'gym_owner', ['owner_id'], ['id'])

    with op.batch_alter_table('edit_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('edit_history_owner_id_fkey'), 'gym_owner', ['owner_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('edit_history_actor_id_fkey'), 'gym_owner', ['actor_id'], ['id'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_member_id_fkey'), 'member', ['member_id'], ['id'])

    # ### end Alembic commands ###
